on: [push, pull_request]

name: build

jobs:
  pre_check:
    name: Precheck
    runs-on: ubuntu-latest
    outputs:
      should_skip_has: ${{ steps.skip_has_check.outputs.should_skip }}
      should_skip_coq: ${{ steps.skip_coq_check.outputs.should_skip }}
    steps:
      - id: skip_has_check
        name: Check if the changes are about Haskell files
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths_ignore: '["coq/**"]'
          do_not_skip: '["pull_request"]'
      - id: skip_coq_check
        name: Check if the changes are about Coq files
        uses: fkirc/skip-duplicate-actions@master
        with:
          paths: '["coq/**", ".github/**"]'
          do_not_skip: '["pull_request"]'

  build-haskell:
    name: Compile Freer Arrows
    runs-on: ubuntu-latest 
    needs: pre_check
    if: ${{ needs.pre_check.outputs.should_skip_has != 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.6'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build

  build-theory:
    name: Proof Check Freer Arrow Theories
    runs-on: ubuntu-latest
    needs: pre_check
    if: ${{ needs.pre_check.outputs.should_skip_coq != 'true' }}
    strategy:
        matrix:
            coq_version:
                - '8.17'
                - '8.18'
                - '8.19'
            ocaml_version: ['default']
        fail-fast: false
    steps:
        - uses: actions/checkout@v4
        - uses: coq-community/docker-coq-action@v1
          with:
            opam_file: 'coq/coq-freer-arrows.opam'
            coq_version: ${{ matrix.coq_version }}
            ocaml_version: ${{ matrix.ocaml_version }}  
