on: [push, pull_request]

name: build

jobs:
  build-haskell:
    name: Compile Freer Arrows
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.5'
          enable-stack: true
          stack-version: 'latest'
      - run: stack build

  build-theory:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            coq_version:
                - '8.17'
                - '8.18'
                - '8.19'
            ocaml_version: ['default']
        fail-fast: false
    steps:
        - uses: actions/checkout@v4
        - uses: coq-community/docker-coq-action@v1
          with:
            opam_file: 'coq/coq-freer-arrows.opam'
            coq_version: ${{ matrix.coq_version }}
            ocaml_version: ${{ matrix.ocaml_version }}  
